export const GET_MUSIC_RECORDS_REQUEST = "GET_MUSIC_RECORDS_REQUEST";
export const GET_MUSIC_RECORDS_SUCCESS = "GET_MUSIC_RECORDS_SUCCESS";
export const GET_MUSIC_RECORDS_FAILURE = "GET_MUSIC_RECORDS_FAILURE";


export const ADD_MUSIC_RECORDS_REQUEST = "ADD_MUSIC_RECORDS_REQUEST";
export const ADD_MUSIC_RECORDS_SUCCESS = "ADD_MUSIC_RECORDS_SUCCESS";
export const ADD_MUSIC_RECORDS_FAILURE = "ADD_MUSIC_RECORDS_FAILURE";


export const UPDATE_MUSIC_RECORDS_REQUEST = "UPDATE_MUSIC_RECORDS_REQUEST";
export const UPDATE_MUSIC_RECORDS_SUCCESS = "UPDATE_MUSIC_RECORDS_SUCCESS";
export const UPDATE_MUSIC_RECORDS_FAILURE = "UPDATE_MUSIC_RECORDS_FAILURE";


export const DELETE_MUSIC_RECORDS_REQUEST = "DELETE_MUSIC_RECORDS_REQUEST";
export const DELETE_MUSIC_RECORDS_SUCCESS = "DELETE_MUSIC_RECORDS_SUCCESS";
export const DELETE_MUSIC_RECORDS_FAILURE = "DELETE_MUSIC_RECORDS_FAILURE";